services:
  - type: web
    name: half-shekel-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: HOST
        value: 0.0.0.0
      - key: TWELVE_DATA_API_KEY
        sync: false
